

public class PlanException extends Exception{
    private int id;

    public PlanException(int id)
    {
        this.id = id;
    }

    public int getId()
    {
        return this.id;
    }

    public String toString()
    {
        return "The Plan ID was not valid and a new ID "+ id +" is generated by admin and assigned for the Plan";
    }
}
