

public class UserException extends Exception{
    private String userName;
    
    public UserException(String userName)
    {
        this.userName = userName;
    }
    
    public String getUserName()
    {
        return this.userName;
    }
    
    public String toString()
    {
        return "The userName was not valid and a new userName "+ userName +" is generated by admin and assigned for the user";
    }
}
